### ISSUE TITLE
CI beüzemelése

### ISSUE THREAD

**Issue by jmate0321** [jmate0321/EmailValidation#1]
@Peter-Nagy, be kellene üzemelni a CI-t.

**Comment by jmate0321** [comment]
f2a77673ea2f8732618e01b72113bb0ebcb61055 Travis hozzáadva

**Comment by jmate0321** [comment]
8b6dba4dddbd230ab468bf20b363e977d33716c3 Ezzel már a tesztek is futtatásra kerülnek

**Comment by szabodora27** [comment]
Feladat ellenőrizve!

**Comment by micskeiz** [comment]
Rendben, a projekt travis oldalát érdemes még a wiki-n belinkelni.
