### ISSUE TITLE
Statikus analízis eszköz futtatása és jelzett hibák javítása

### ISSUE THREAD

**Issue by xGabax** [jmate0321/EmailValidation#2]

**Comment by xGabax** [comment]
https://github.com/jmate0321/EmailValidation/commit/8623d74fdbb52dd38d9308f25bc2add7fe3d9985 Kód analízis bekapcsolva

https://github.com/jmate0321/EmailValidation/commit/e776f5c0a45bb7b77cad57e03a6f33e8565fc3a1
TestResult.xaml törölve

**Comment by xGabax** [comment]
https://github.com/jmate0321/EmailValidation/commit/af0c0deb7ebebbd0754cfedbb31220f0df8ce27e Hibák javítva

**Comment by jmate0321** [comment]
`Code Analysis Complete -- 0 error(s), 0 warning(s)`
Ellenőrizve!

**Comment by micskeiz** [comment]
OK.
