### ISSUE TITLE
Tesztek hozzáadása

### ISSUE THREAD

**Issue by jmate0321** [jmate0321/EmailValidation#4]
A meglévő teszteket ki kell egészíteni

**Comment by jmate0321** [comment]
1bb9f1dd8a993c234ff07532907d104909d10426 új tesztek felvéve

**Comment by jmate0321** [comment]
8381a3cb975654e52e7cacd679f82402e15362b6 teszt framework frissítve, mostmár a VS is felismeri a teszteket

**Comment by Peter-Nagy** [comment]
Két új teszt hozzáadva: https://github.com/jmate0321/EmailValidation/commit/9602f8ef0f0f45769ee34ec72d39188d1fc432d0 https://github.com/jmate0321/EmailValidation/commit/b35a8b48ca33d91555507f13af63a881e05e0baf

**Comment by xGabax** [comment]
Még egy teszt hozzáadva: https://github.com/jmate0321/EmailValidation/commit/c1698cab4a0dc3fac41e2287d9fb2384a378f5be

**Comment by szabodora27** [comment]
Újabb 5 teszt: https://github.com/jmate0321/EmailValidation/commit/1fa5f0b2281f7a127a77a0f6b8f4950dc592ef1d https://github.com/jmate0321/EmailValidation/commit/f39c34bb0529e28c6231955bd9fab1c3eb8e2bfc https://github.com/jmate0321/EmailValidation/commit/046e998bb2d6c0439fa037eff8426daef69539a3
=> ipv6 lefedve

**Comment by szabodora27** [comment]
Még 3 teszt: https://github.com/jmate0321/EmailValidation/commit/74304ff3b3c213b1228a9ecc27fab2beb614aca7 https://github.com/jmate0321/EmailValidation/commit/30d2421580b5f67945d0083167911e3682306861
=> 100%-os tesztfedettség elérése

**Comment by jmate0321** [comment]
`COVERAGE INCREASED (+0.4%) TO 100.0%`

Ellenőrzive, kész vagyunk.
