### ISSUE TITLE
Kódlefedettség mérése

### ISSUE THREAD

**Issue by jmate0321** [jmate0321/EmailValidation#6]

**Comment by jmate0321** [comment]
d2e94ac751359f7ddf00270150122ea404551675 badge hozzáadva a README-hez

**Comment by jmate0321** [comment]
f8bf50777c02226e8b165ef0642ffa967cf4ce33 ezzel véglegesítve a kódlefedettség ellenőrzés

**Comment by szabodora27** [comment]
feladat ellenőrizve!

**Comment by jmate0321** [comment]
cfb0f78df4c23a20bf099b7b19db13571f3feeaf
e21f83ca287e1d0d247f92e27e9433b85f3c0df2
0ba4cce8cc9d058612128582bad9e6784af3f9b7

batch fájl kiegészítve, így pontosabb eredményt kapunk
